"""Layer 4 — Plan generation payload schemas.

See `aidstation-sources/Layer4_Spec.md` §7 for the contract; this package
implements the typed schemas + §7.12 cross-field invariants. Domain-level
training-load / ACWR / injury rules live in the §5.4 validator harness
(Step 3 of §14.3.4), not here.
"""

from layer4.payload import (
    CadenceTarget,
    CardioBlock,
    ClimbingGradeTarget,
    Contingency,
    FuelingStrategy,
    HRTarget,
    IntensityTarget,
    KitItem,
    Layer4Payload,
    Observation,
    PaceTarget,
    PacingStrategy,
    PhaseSpec,
    PhaseStructure,
    PlanSession,
    PowerTarget,
    RPETarget,
    RacePlan,
    RaceSegment,
    RaceWeekBrief,
    RuleFailure,
    SeamReview,
    SessionPhaseMetadata,
    ShapeOverride,
    StrengthExercise,
    StrokeRateTarget,
    SwimPaceTarget,
    SynthesisMetadata,
    TransitionSpec,
    ValidatorResult,
    VerticalRateTarget,
)

__all__ = [
    "CadenceTarget",
    "CardioBlock",
    "ClimbingGradeTarget",
    "Contingency",
    "FuelingStrategy",
    "HRTarget",
    "IntensityTarget",
    "KitItem",
    "Layer4Payload",
    "Observation",
    "PaceTarget",
    "PacingStrategy",
    "PhaseSpec",
    "PhaseStructure",
    "PlanSession",
    "PowerTarget",
    "RPETarget",
    "RacePlan",
    "RaceSegment",
    "RaceWeekBrief",
    "RuleFailure",
    "SeamReview",
    "SessionPhaseMetadata",
    "ShapeOverride",
    "StrengthExercise",
    "StrokeRateTarget",
    "SwimPaceTarget",
    "SynthesisMetadata",
    "TransitionSpec",
    "ValidatorResult",
    "VerticalRateTarget",
]
